# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PickEau
                                 A QGIS plugin
 L'extension PickEau permet de télécharger automatiquement les chroniques
 de niveau piézométrique et de qualité des eaux souterraines mises à
 disposition par les API Hub'Eau (https://hubeau.eaufrance.fr/).
 PickEau permet ensuite de tracer les chroniques de manière interactive,
 d'afficher leurs statistiques et leurs tendances, et de partager avec
 les autres utilisateurs des commentaires sur la qualité des données. 
 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-08-21
        copyright            : (C) 2019 by BRGM
        email                : 
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from .pickeau import PickEau


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PickEau class from file pickeau.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    
    return PickEau(iface)
